### ISSUE TITLE
To Contribute?

### ISSUE THREAD

**Issue by bogdanpolak** [segovoni/delphi-demos#1]
@segovoni is this project open for the contributions? Cant find any suggestion in the README

**Comment by segovoni** [comment]
Hi @bogdanpolak, thanks for your comment. Sure, the repository delphi-demos is open for contributions, it's a very simple project that I use for demo and courses on Delphi. You are welcome!

**Comment by segovoni** [comment]
Updated the repository's README.md and added guidelines for contributing.
